browser: chrome
headless: false
device: Desktop Chrome
environment: qa
url: https://example.cypress.io/todo#/
#Report related configurations
reportTheme: 'bootstrap' # 'bootstrap' or 'simple' or 'foundation' or 'hierarchy'
reportJson: 'src/resources/reports/results.json'
reportPath: 'src/resources/reports/results.html'
reportTitle: 'Test Summary Report'
reportLaunch: true